### ISSUE TITLE
can't find Proxy::PluginValidators

### ISSUE THREAD

**Issue by tpdownes** [theforeman/smart_proxy_dhcp_infoblox#19]
I was running a previous version of `smart_proxy_dhcp_infoblox` and `smart_proxy_dns_infoblox`. I updated by running `sudo -u foreman bundle update` with this as the contents of `~foreman/bundler.d/Gemfile.local.rb`
```
gem 'smart_proxy_dhcp_infoblox'
gem 'smart_proxy_dns_infoblox'
gem 'infoblox'
```
Now I can't get foreman to start again. It appears not to be able to find Proxy::PluginValidators although I am running Foreman 1.13.1.
```
Web application could not be started

uninitialized constant Proxy::PluginValidators (NameError)
  /usr/share/foreman/vendor/ruby/2.1.0/gems/smart_proxy_dhcp_infoblox-0.0.5/lib/smart_proxy_dhcp_infoblox/record_type_validator.rb:2:in `<module:Infoblox>'
  /usr/share/foreman/vendor/ruby/2.1.0/gems/smart_proxy_dhcp_infoblox-0.0.5/lib/smart_proxy_dhcp_infoblox/record_type_validator.rb:1:in `<top (required)>'
  /usr/share/foreman/vendor/ruby/2.1.0/gems/smart_proxy_dhcp_infoblox-0.0.5/lib/smart_proxy_dhcp_infoblox.rb:8:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `require'
  /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `block (2 levels) in require'
  /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `each'
  /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block in require'
  /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `each'
  /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `require'
  /usr/lib/ruby/vendor_ruby/bundler.rb:133:in `require'
  /usr/share/foreman/config/application.rb:36:in `<top (required)>'
  /usr/share/foreman/config/environment.rb:2:in `require'
  /usr/share/foreman/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/share/foreman/vendor/ruby/2.1.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/share/foreman/vendor/ruby/2.1.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
```

**Comment by tpdownes** [comment]
Resolved by user. Not a bug.
